import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

import {
  Button,
  Box,
  Flex,
  Spacer,
  HStack,
  Select,
  Input,
} from "@chakra-ui/react";
import html2canvas from "html2canvas";
import jsPDF from "jspdf";
import { useRef } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const pdfRef = useRef<HTMLDivElement | null>(null);
  const downloadPDF = () => {
    const input = pdfRef.current as HTMLElement;
    html2canvas(input).then((canvas) => {
      const imgData = canvas.toDataURL("image/png");
      const pdf = new jsPDF("p", "mm", "a4", true);
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();
      const imgWidth = canvas.width;
      const imgHeight = canvas.height;
      const ratio = Math.min(pdfWidth / imgWidth, pdfHeight / imgHeight);
      const imgX = (pdfWidth - imgWidth * ratio) / 2;
      const imgY = 30;
      const timestamp = new Date().toLocaleString();
      pdf.addImage(
        imgData,
        "PNG",
        imgX,
        imgY,
        imgWidth * ratio,
        imgHeight * ratio
      );
      pdf.save(`assessment-result-${timestamp}.pdf`);
    });
  };

  return (
    <>
      <Head>
        <title>Pdf Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Manrope:wght@200;300;400;500;700&family=Poppins:wght@100;400;500;700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main className="pdf-body" ref={pdfRef}>
        <div className="logo">
          <img src="/logo.svg" />
        </div>

        <header>Assesment Score Sheet</header>
        <HStack spacing="24px" className="grade-section" mb={4}>
          <h4>Student Name:</h4>
          <Input width="220px" />
        </HStack>
        <div className="score-grade">
          <HStack spacing="5px">
            <h4>Further Mathematics:</h4>
            <Select placeholder="Select Grade" width="160px">
              <option value="option1">A1</option>
              <option value="option2">A2</option>
              <option value="option3">B1</option>
              <option value="option3">B2</option>
              <option value="option3">B3</option>
              <option value="option3">C1</option>
              <option value="option3">C2</option>
              <option value="option3">C3</option>
              <option value="option3">D1</option>
              <option value="option3">D2</option>
              <option value="option3">E</option>
              <option value="option3">F</option>
            </Select>
          </HStack>
          <br />

          <HStack spacing="60px">
            <h4>Mathematics:</h4>
            <Select placeholder="Select Grade" width="160px">
              <option value="option1">A1</option>
              <option value="option2">A2</option>
              <option value="option3">B1</option>
              <option value="option3">B2</option>
              <option value="option3">B3</option>
              <option value="option3">C1</option>
              <option value="option3">C2</option>
              <option value="option3">C3</option>
              <option value="option3">D1</option>
              <option value="option3">D2</option>
              <option value="option3">E</option>
              <option value="option3">F</option>
            </Select>
          </HStack>
          <br />
          <HStack spacing="60px">
            <h4>Geograpghy:</h4>
            <Select placeholder="Select Grade" width="160px">
              <option value="option1">A1</option>
              <option value="option2">A2</option>
              <option value="option3">B1</option>
              <option value="option3">B2</option>
              <option value="option3">B3</option>
              <option value="option3">C1</option>
              <option value="option3">C2</option>
              <option value="option3">C3</option>
              <option value="option3">D1</option>
              <option value="option3">D2</option>
              <option value="option3">E</option>
              <option value="option3">F</option>
            </Select>
          </HStack>
          <br />
          <HStack spacing="70px">
            <h4>Chemistry:</h4>
            <Select placeholder="Select Grade" width="160px">
              <option value="option1">A1</option>
              <option value="option2">A2</option>
              <option value="option3">B1</option>
              <option value="option3">B2</option>
              <option value="option3">B3</option>
              <option value="option3">C1</option>
              <option value="option3">C2</option>
              <option value="option3">C3</option>
              <option value="option3">D1</option>
              <option value="option3">D2</option>
              <option value="option3">E</option>
              <option value="option3">F</option>
            </Select>
          </HStack>
          <br />
          <HStack spacing="100px">
            <h4>English:</h4>
            <Select placeholder="Select Grade" width="160px">
              <option value="option1">A1</option>
              <option value="option2">A2</option>
              <option value="option3">B1</option>
              <option value="option3">B2</option>
              <option value="option3">B3</option>
              <option value="option3">C1</option>
              <option value="option3">C2</option>
              <option value="option3">C3</option>
              <option value="option3">D1</option>
              <option value="option3">D2</option>
              <option value="option3">E</option>
              <option value="option3">F</option>
            </Select>
          </HStack>
          <br />
          <HStack spacing="100px">
            <h4>Physics:</h4>
            <Select placeholder="Select Grade" width="160px">
              <option value="option1">A1</option>
              <option value="option2">A2</option>
              <option value="option3">B1</option>
              <option value="option3">B2</option>
              <option value="option3">B3</option>
              <option value="option3">C1</option>
              <option value="option3">C2</option>
              <option value="option3">C3</option>
              <option value="option3">D1</option>
              <option value="option3">D2</option>
              <option value="option3">E</option>
              <option value="option3">F</option>
            </Select>
          </HStack>
          <br />

          <HStack spacing="100px">
            <h4>Biology:</h4>
            <Select placeholder="Select Grade" width="160px">
              <option value="option1">A1</option>
              <option value="option2">A2</option>
              <option value="option3">B1</option>
              <option value="option3">B2</option>
              <option value="option3">B3</option>
              <option value="option3">C1</option>
              <option value="option3">C2</option>
              <option value="option3">C3</option>
              <option value="option3">D1</option>
              <option value="option3">D2</option>
              <option value="option3">E</option>
              <option value="option3">F</option>
            </Select>
          </HStack>
          <br />

          <HStack spacing="100px">
            <h4>Fisheries:</h4>
            <Select placeholder="Select Grade" width="160px">
              <option value="option1">A1</option>
              <option value="option2">A2</option>
              <option value="option3">B1</option>
              <option value="option3">B2</option>
              <option value="option3">B3</option>
              <option value="option3">C1</option>
              <option value="option3">C2</option>
              <option value="option3">C3</option>
              <option value="option3">D1</option>
              <option value="option3">D2</option>
              <option value="option3">E</option>
              <option value="option3">F</option>
            </Select>
          </HStack>
        </div>

        <div className="export-btn">
          <Button colorScheme="blue" onClick={downloadPDF}>
            Download Result
          </Button>
        </div>
      </main>
    </>
  );
}
